apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro-opti-dataprep
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pro-opti-dataprep
  template:
    metadata:
      labels:
        app: pro-opti-dataprep
    spec:
      initContainers:
        - env:
            - name: PG_DATABASE
              value: app
            - name: PG_HOST
              value: acid-minimal-cluster.default.svc.cluster.local
            - name: PG_PORT
              value: "5432"
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                    name: postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
                    key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=Opti,service.instance.id=0"
            - name: OTEL_SERVICE_NAME
              value: "live-ingestion"
            - name: SITE
              value: hvc
          image: localhost:5000/datastore:tag
          name: pro-opti-db-initialize
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: Always
      containers:
        - env:
            - name: PG_DATABASE
              value: postgres
            - name: PG_HOST
              value: acid-minimal-cluster.default.svc.cluster.local
            - name: PG_PORT
              value: "5432"
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=Opti,service.instance.id=0"
            - name: OTEL_SERVICE_NAME
              value: "live-ingestion"
            - name: SITE
              value: hvc
          image: localhost:5000/datastore:tag
          command: ["python","-c","pass"]
          name: pro-opti-dataprep
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: Always