apiVersion: batch/v1
kind: CronJob
metadata:
  name: pro-opti-inference-cron
  namespace: default  # Change to your desired namespace
spec:
  suspend: true #TODO remove when real images present
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pro-opti-inference-optimizer
              image: localhost:5000/inference:tag
              imagePullPolicy: Always
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "1"
                limits:
                  memory: "1Gi"
                  cpu: "1"
              env:
                - name: ENVIRONMENT
                  value: qa
                - name: PG_DATABASE
                  value: postgres
                - name: PG_HOST
                  value: acid-minimal-cluster.default.svc.cluster.local
                - name: PG_PORT
                  value: "5432"
                - name: PG_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
                      key: username
                - name: PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
                      key: password
                - name: MATERIALIZER_ENDPOINT
                  value: pro-opti-materializer
                - name: POD_UID
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.uid
          restartPolicy: OnFailure
