apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pro-opti-materializer
  name: pro-opti-materializer
  namespace: default 
spec:
  replicas: 1 #TODO set to 1 when real images present
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pro-opti-materializer
  template:
    metadata:
      labels:
        app: pro-opti-materializer
    spec:
      containers:
        - env:
            - name: ENVIRONMENT
              value: qa
            - name: PG_DATABASE
              value: postgres
            - name: PG_HOST
              value: acid-minimal-cluster.default.svc.cluster.local
            - name: PG_PORT
              value: "5432"
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: TDP_EH_FQDN
              value: des-ent-qa-cus-cloud-eventhub-001.servicebus.windows.net
            - name: TDP_EH_NAME
              value: hvc-pro-data
            - name: DEBUG
              value: 'True'
            - name: LOCAL_DEV
              value: 'True' 
          image: localhost:5000/materializer:tag
          name: pro-opti-materializer
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8000
            timeoutSeconds: 5
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8000
            timeoutSeconds: 5
            initialDelaySeconds: 60
          imagePullPolicy: Always
