apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances:  1
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  preparedDatabases:
    app:
      defaultUsers: true
      extensions:
        timescaledb: public
  postgresql:
    version: "17"
    parameters:
      shared_preload_libraries: "bg_mon,pg_stat_statements,timescaledb"
      # Expressly tell the database instance to unlock the full feature set
      timescaledb.license: "timescale"

  env:
    - name: TIMESCALEDB_APACHE_ONLY
      value: "false"
