apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-cronjobs
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: cronjob-reader
  apiGroup: rbac.authorization.k8s.io
