apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cronjob-reader
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs","job","pod"]
  verbs: ["get", "list", "watch", "create"]
