apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cronjob-reader
  namespace: default
rules:
- apiGroups: ["batch","core"]
  resources: ["cronjobs", "jobs", "pods", "services"]
  verbs: ["get", "list", "watch", "create"]
