apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plant-opti
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rohitkhazanchi121/argocd.git
    path: jobs
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

